// action - account reducer
/* eslint-disable camelcase */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILED = 'SEND_OTP_FAILED';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const ROlE_REQUEST = 'ROlE_REQUEST';
export const ROlE_SUCCESS = 'ROlE_SUCCESS';
export const ROlE_FAILED = 'ROlE_FAILED';

export const DELETE_ROlE_REQUEST = 'DELETE_ROlE_REQUEST';
export const DELETE_ROlE_SUCCESS = 'DELETE_ROlE_SUCCESS';
export const DELETE_ROlE_FAILED = 'DELETE_ROlE_FAILED';

export const SAVE_ROlE_REQUEST = 'SAVE_ROlE_REQUEST';
export const SAVE_ROlE_SUCCESS = 'SAVE_ROlE_SUCCESS';
export const SAVE_ROlE_FAILED = 'SAVE_ROlE_FAILED';

export const SECTION_REQUEST = 'SECTION_REQUEST';
export const SECTION_SUCCESS = 'SECTION_SUCCESS';
export const SECTION_FAILED = 'SECTION_FAILED';

export const SAVE_SECTION_REQUEST = 'SAVE_SECTION_REQUEST';
export const SAVE_SECTION_SUCCESS = 'SAVE_SECTION_SUCCESS';
export const SAVE_SECTION_FAILED = 'SAVE_SECTION_FAILED';

export const DELETE_SECTION_REQUEST = 'DELETE_SECTION_REQUEST';
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS';
export const DELETE_SECTION_FAILED = 'DELETE_DSECTION_FAILED';

export const DEPARTMENT_REQUEST = 'DEPARTMENT_REQUEST';
export const DEPARTMENT_SUCCESS = 'DEPARTMENT_SUCCESS';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';

export const SAVE_DEPARTMENT_REQUEST = 'SAVE_DEPARTMENT_REQUEST';
export const SAVE_DEPARTMENT_SUCCESS = 'SAVE_DEPARTMENT_SUCCESS';
export const SAVE_DEPARTMENT_FAILED = 'SAVE_DEPARTMENT_FAILED';

export const DELETE_DEPARTMENT_REQUEST = 'DELETE_DEPARTMENT_REQUEST';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILED = 'DELETE_DEPARTMENT_FAILED';

export const CORRIDOR_REQUEST = 'CORRIDOR_REQUEST';
export const CORRIDOR_SUCCESS = 'CORRIDOR_SUCCESS';
export const CORRIDOR_FAILED = 'CORRIDOR_FAILED';

export const SAVE_CORRIDOR_REQUEST = 'SAVE_CORRIDOR_REQUEST';
export const SAVE_CORRIDOR_SUCCESS = 'SAVE_CORRIDOR_SUCCESS';
export const SAVE_CORRIDOR_FAILED = 'SAVE_CORRIDOR_FAILED';

export const DELETE_CORRIDOR_REQUEST = 'DELETE_CORRIDOR_REQUEST';
export const DELETE_CORRIDOR_SUCCESS = 'DELETE_CORRIDOR_SUCCESS';
export const DELETE_CORRIDOR_FAILED = 'DELETE_CORRIDOR_FAILED';

export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAILED = 'CATEGORY_FAILED';

export const SAVE_CATEGORY_REQUEST = 'SAVE_CATEGORY_REQUEST';
export const SAVE_CATEGORY_SUCCESS = 'SAVE_CATEGORY_SUCCESS';
export const SAVE_CATEGORY_FAILED = 'SAVE_CATEGORY_FAILED';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

export const SUB_CATEGORY_REQUEST = 'SUB_CATEGORY_REQUEST';
export const SUB_CATEGORY_SUCCESS = 'SUB_CATEGORY_SUCCESS';
export const SUB_CATEGORY_FAILED = 'SUB_CATEGORY_FAILED';

export const SAVE_SUB_CATEGORY_REQUEST = 'SAVE_SUB_CATEGORY_REQUEST';
export const SAVE_SUB_CATEGORY_SUCCESS = 'SAVE_SUB_CATEGORY_SUCCESS';
export const SAVE_SUB_CATEGORY_FAILED = 'SAVE_SUB_CATEGORY_FAILED';

export const DELETE_SUB_CATEGORY_REQUEST = 'DELETE_SUB_CATEGORY_REQUEST';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAILED = 'DELETE_SUB_CATEGORY_FAILED';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const TICKET_REQUEST = 'TICKET_REQUEST';
export const TICKET_SUCCESS = 'TICKET_SUCCESS';
export const TICKET_FAILED = 'TICKET_FAILED';

export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAILED = 'CREATE_TICKET_FAILED';

export const TICKET_BYID_REQUEST = 'TICKET_BYID_REQUEST';
export const TICKET_BYID_SUCCESS = 'TICKET_BYID_SUCCESS';
export const TICKET_BYID_FAILED = 'TICKET_BYID_FAILED';

export const DELETE_TICKET_REQUEST = 'DELETE_TICKET_REQUEST';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAILED = 'DELETE_TICKET_FAILED';

export const STATUS_REQUEST = 'STATUS_REQUEST';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILED = 'STATUS_FAILED';

export const SAVE_STATUS_REQUEST = 'SAVE_STATUS_REQUEST';
export const SAVE_STATUS_SUCCESS = 'SAVE_STATUS_SUCCESS';
export const SAVE_STATUS_FAILED = 'SAVE_STATUS_FAILED';

export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAILED = 'DELETE_STATUS_FAILED';

export const PRIORITY_REQUEST = 'PRIORITY_REQUEST';
export const PRIORITY_SUCCESS = 'PRIORITY_SUCCESS';
export const PRIORITY_FAILED = 'PRIORITY_FAILED';

export const SAVE_PRIORITY_REQUEST = 'SAVE_PRIORITY_REQUEST';
export const SAVE_PRIORITY_SUCCESS = 'SAVE_PRIORITY_SUCCESS';
export const SAVE_PRIORITY_FAILED = 'SAVE_PRIORITY_FAILED';

export const DELETE_PRIORITY_REQUEST = 'DELETE_PRIORITY_REQUEST';
export const DELETE_PRIORITY_SUCCESS = 'DELETE_PRIORITY_SUCCESS';
export const DELETE_PRIORITY_FAILED = 'DELETE_PRIORITY_FAILED';

export const PERMISSION_REQUEST = 'PERMISSION_REQUEST';
export const PERMISSION_SUCCESS = 'PERMISSION_SUCCESS';
export const PERMISSION_FAILED = 'PERMISSION_FAILED';

export const SAVE_PERMISSION_REQUEST = 'SAVE_PERMISSION_REQUEST';
export const SAVE_PERMISSION_SUCCESS = 'SAVE_PERMISSION_SUCCESS';
export const SAVE_PERMISSION_FAILED = 'SAVE_PERMISSION_FAILED';

export const DELETE_PERMISSION_REQUEST = 'DELETE_PERMISSION_REQUEST';
export const DELETE_PERMISSION_SUCCESS = 'DELETE_PERMISSION_SUCCESS';
export const DELETE_PERMISSION_FAILED = 'DELETE_PERMISSION_FAILED';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const FIREBASE_STATE_CHANGED = 'FIREBASE_STATE_CHANGED';
